field: dcc8b04d-d98b-48c7-b3b1-c7cd65e1f96a # Leistungen
fieldLayouts:
  49772105-21f8-4c3c-946b-99defea5796a:
    tabs:
      -
        elements:
          -
            fieldUid: 96128586-add9-4174-90de-9ee5861e786c # Lead
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 66247b49-40a2-4fe8-9f96-07e0c4288932 # Leistungen
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  66247b49-40a2-4fe8-9f96-07e0c4288932: # Leistungen
    contentColumnType: text
    fieldGroup: null
    handle: services
    instructions: ''
    name: Leistungen
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: ''
      removeInlineStyles: '1'
      removeNbsp: ''
      showHtmlButtonForNonAdmins: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  96128586-add9-4174-90de-9ee5861e786c: # Lead
    contentColumnType: text
    fieldGroup: null
    handle: lead
    instructions: ''
    name: Lead
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: ''
      removeInlineStyles: '1'
      removeNbsp: ''
      showHtmlButtonForNonAdmins: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: service
name: Leistung
sortOrder: 1
