field: 114da0c0-1d67-43e9-9966-1e7967900a92 # Kleiner Slider
fieldLayouts:
  4ef6dedc-8c94-4b5f-a1f8-cc36913f324f:
    tabs:
      -
        elements:
          -
            fieldUid: 8028aa1c-bcf5-40fc-906a-fdd777682c1f # Bild
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  8028aa1c-bcf5-40fc-906a-fdd777682c1f: # Bild
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Bild
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:1441d23a-77fd-4cb1-9e07-7deda2c44aca' # Bilder
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: 'Bild auswählen'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:1441d23a-77fd-4cb1-9e07-7deda2c44aca' # Bilder
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:1441d23a-77fd-4cb1-9e07-7deda2c44aca' # Bilder
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: slide
name: Slide
sortOrder: 1
