field: 971783c5-870d-4987-8ec2-ef8a766df4a5 # Slider
fieldLayouts:
  8c852083-f938-4ed6-9c7e-27d63a3bf053:
    tabs:
      -
        elements:
          -
            fieldUid: 2ed64c05-eb8c-4d88-9ad0-3e29542829b8 # Bild
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  2ed64c05-eb8c-4d88-9ad0-3e29542829b8: # Bild
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Bild
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:1441d23a-77fd-4cb1-9e07-7deda2c44aca' # Bilder
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: 'Bild auswählen'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:1441d23a-77fd-4cb1-9e07-7deda2c44aca' # Bilder
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:1441d23a-77fd-4cb1-9e07-7deda2c44aca' # Bilder
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: slide
name: Slide
sortOrder: 1
