field: a2ff65ee-37ac-459a-b8b6-260a51655430 # Content-Builder
fieldLayouts:
  809603b1-6927-45a1-9f80-0b886ed1e46a:
    tabs:
      -
        elements:
          -
            fieldUid: fac07c15-8566-4efd-baab-35b5d55b1f8e # Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  fac07c15-8566-4efd-baab-35b5d55b1f8e: # Text
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes:
        - d46bc7c1-9ab9-4f32-81b3-ef71a64dfcce # Dateien
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: ''
      removeInlineStyles: '1'
      removeNbsp: ''
      showHtmlButtonForNonAdmins: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: text
name: Text
sortOrder: 1
