field: a2ff65ee-37ac-459a-b8b6-260a51655430 # Content-Builder
fieldLayouts:
  3416ff81-3184-4a19-a02b-6b8fb6fc4b1d:
    tabs:
      -
        elements:
          -
            fieldUid: 4ed46586-0a29-4c32-b6d9-55057597ead9 # Text 1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 60f90423-2534-4e9e-88d8-6921be51f41a # Text 2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  4ed46586-0a29-4c32-b6d9-55057597ead9: # Text 1
    contentColumnType: text
    fieldGroup: null
    handle: text1
    instructions: ''
    name: 'Text 1'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: ''
      removeInlineStyles: '1'
      removeNbsp: ''
      showHtmlButtonForNonAdmins: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  60f90423-2534-4e9e-88d8-6921be51f41a: # Text 2
    contentColumnType: text
    fieldGroup: null
    handle: text2
    instructions: ''
    name: 'Text 2'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: ''
      removeInlineStyles: '1'
      removeNbsp: ''
      showHtmlButtonForNonAdmins: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: textText
name: 'Text + Text'
sortOrder: 2
