fieldLayouts:
  4b461a66-c0c5-48b6-af03-f800e0d79795:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 268b1051-db1a-4ed1-903d-ffe1ac06faef # Menu-Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Inhalt
        sortOrder: 1
handle: serviceMenuItem
hasTitleField: false
name: Service-Menü-Item
section: 34239d13-b446-4707-8047-5af14e0c6bd2 # Service-Menü
sortOrder: 1
titleFormat: '{menuLink.getText()}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
