contentColumnType: string
fieldGroup: 163d7a3b-3435-4fe0-99ed-4afd32dfd8d5 # Footer
handle: footerMap
instructions: ''
name: Map
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:1441d23a-77fd-4cb1-9e07-7deda2c44aca' # Bilder
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: 'Bild auswählen'
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:1441d23a-77fd-4cb1-9e07-7deda2c44aca' # Bilder
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:1441d23a-77fd-4cb1-9e07-7deda2c44aca' # Bilder
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
