contentColumnType: string
fieldGroup: c4b19722-35a5-4b16-95eb-95bae393243d # Hero
handle: heroSlider
instructions: ''
name: Slider
searchable: false
settings:
  contentTable: '{{%matrixcontent_heroslider}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
