contentColumnType: text
fieldGroup: acfbef1a-7c89-4a72-ae09-969d22e5ac18 # Menü
handle: menuLink
instructions: ''
name: Menu-Link
searchable: false
settings:
  allowCustomText: '1'
  allowTarget: '1'
  allowedLinkNames: '*'
  autoNoReferrer: '1'
  defaultLinkName: entry
  defaultText: ''
  enableAriaLabel: ''
  enableTitle: ''
  typeSettings:
    __assoc__:
      -
        - asset
        -
          __assoc__:
            -
              - sources
              - '*'
            -
              - allowCustomQuery
              - ''
      -
        - user
        -
          __assoc__:
            -
              - sources
              - '*'
            -
              - allowCustomQuery
              - ''
      -
        - entry
        -
          __assoc__:
            -
              - sources
              -
                - 'single:009214d7-e8e7-4fb1-a036-0c05208d6cac' # Startseite
                - 'section:481c6233-0299-44fe-a150-d7432630deab' # Seitenbaum
            -
              - allowCustomQuery
              - '1'
      -
        - category
        -
          __assoc__:
            -
              - sources
              - '*'
            -
              - allowCustomQuery
              - ''
      -
        - site
        -
          __assoc__:
            -
              - sites
              - '*'
      -
        - custom
        -
          __assoc__:
            -
              - disableValidation
              - ''
            -
              - allowAliases
              - ''
      -
        - email
        -
          __assoc__:
            -
              - disableValidation
              - ''
            -
              - allowAliases
              - ''
      -
        - tel
        -
          __assoc__:
            -
              - disableValidation
              - ''
            -
              - allowAliases
              - ''
      -
        - url
        -
          __assoc__:
            -
              - disableValidation
              - ''
            -
              - allowAliases
              - ''
translationKeyFormat: null
translationMethod: none
type: typedlinkfield\fields\LinkField
