contentColumnType: text
fieldGroup: 73486341-6e47-4943-95ab-1c8bc49e345f # Projekte
handle: projectSlider2Headline
instructions: ''
name: 'Headline kleiner Slider'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
