contentColumnType: string
fieldGroup: 73486341-6e47-4943-95ab-1c8bc49e345f # Projekte
handle: projectSlider
instructions: ''
name: Slider
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:1441d23a-77fd-4cb1-9e07-7deda2c44aca' # Bilder
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: 'Bilder auswählen'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:1441d23a-77fd-4cb1-9e07-7deda2c44aca' # Bilder
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:1441d23a-77fd-4cb1-9e07-7deda2c44aca' # Bilder
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
