dateModified: 1623075905
email:
  fromEmail: urs@21sieben.de
  fromName: 'Craft Starter 2021'
  transportType: craft\mail\transportadapters\Sendmail
plugins:
  command-palette:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
    settings:
      elementSearchElementTypes:
        __assoc__:
          -
            - asset
            -
              __assoc__:
                -
                  - elementType
                  - Asset
                -
                  - enabled
                  - ''
          -
            - category
            -
              __assoc__:
                -
                  - elementType
                  - Kategorie
                -
                  - enabled
                  - '1'
          -
            - entry
            -
              __assoc__:
                -
                  - elementType
                  - Eintrag
                -
                  - enabled
                  - '1'
          -
            - globalset
            -
              __assoc__:
                -
                  - elementType
                  - 'Globaler Satz'
                -
                  - enabled
                  - ''
          -
            - matrixblock
            -
              __assoc__:
                -
                  - elementType
                  - Matrix-Block
                -
                  - enabled
                  - ''
          -
            - tag
            -
              __assoc__:
                -
                  - elementType
                  - Schlagwort
                -
                  - enabled
                  - ''
          -
            - user
            -
              __assoc__:
                -
                  - elementType
                  - Benutzer
                -
                  - enabled
                  - '1'
      pluginName: ''
      theme: ''
  dumper:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  empty-coalesce:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  expanded-singles:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  seo:
    edition: standard
    enabled: true
    schemaVersion: 3.2.0
    settings:
      description: ''
      facebookAppId: ''
      metaTemplate: _meta.twig
      removeAlternateUrls: ''
      robots:
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
      robotsTxt: "{# Sitemap URL #}\r\nSitemap: {{ url(seo.sitemapName ~ '.xml') }}\r\n\r\n{# Disallows #}\r\n{% if craft.app.config.env != 'production' %}\r\n\r\n{# Disallow access to everything when NOT in production #}\r\nUser-agent: *\r\nDisallow: /\r\n\r\n{% else %}\r\n\r\n{# Disallow access to cpresources/ when live #}\r\nUser-agent: *\r\nDisallow: /cpresources/\r\n\r\n{% endif %}"
      sitemapLimit: '1000'
      sitemapName: sitemap
      socialImage: ''
      title:
        -
          __assoc__:
            -
              - key
              - '1'
            -
              - locked
              - '0'
            -
              - template
              - '{title}'
        -
          __assoc__:
            -
              - key
              - '2'
            -
              - locked
              - '0'
            -
              - template
              - ' - {{ siteName }}'
      titleSuffix: null
      twitterHandle: ''
  typedlinkfield:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: 'EH Innenarchitektur'
  retryDuration: null
  schemaVersion: 3.6.8
  timeZone: Europe/Berlin
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
