fieldLayouts:
  0fecb7cb-ddb2-444f-aaa2-9236cfd41ac1:
    tabs:
      -
        elements:
          -
            fieldUid: 161941d2-310a-4dc4-84f8-750af394454c # Lead
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9ae8736f-64b4-4555-9161-2b45e1a6dad8 # Adresse
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2912fb8f-0022-4bf9-9a06-3576f887a666 # Map
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Inhalt
        sortOrder: 1
handle: footer
name: Footer
