enableVersioning: true
handle: projects
name: Projekte
propagationMethod: all
siteSettings:
  335a10e2-8b40-46e0-8f05-2a0883f6e52a: # EH Innenarchitektur
    enabledByDefault: true
    hasUrls: true
    template: _routers/page
    uriFormat: 'projekte/{slug}'
structure:
  maxLevels: 1
  uid: cceb9cb3-2175-46e2-8313-66c34dcf1f17
type: structure
